package:
  name: cuda-version
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: 5db25d4fd138013b563f9a3d1d87f7de7df1dac014fd4cccdfbb3435a5cff761

build:
  number: 0
  noarch: generic

requirements:
  run_constrained:
    {% if version is defined %}                # Safe-guard for early parsing
    - __cuda >={{ version.split(".", 1)[0] }}  # Major version is lower bound
    - cudatoolkit {{ version }}                # Align `cudatoolkit` version
    {% endif %}

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: A meta-package for pinning to a CUDA release version
  description: |
    A meta-package for pinning to a CUDA release version
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - adibbley
    - jakirkham
